### ISSUE TITLE
Line Level Outputs Not Muted

### ISSUE THREAD

**Issue by boulwarek** [micro-nova/AmpliPi#245]
I am powering in-wall speakers with the amplified outputs and feeding a subwoofer amplifier with the line level outputs on the same zone. When I mute the zone, the line level outputs continue to play (Just the subwoofers). The only way I have found to get around this is assign the zone to a source with nothing playing.
I did some additional testing and ran just the line level outputs to a receiver with a speakers connected. Nothing was connected to the amplified outputs. This also failed to mute when muting the zone.

Some additional thoughts. Since these can obviously be controlled separately, would it be possible to create a 12 zone system by utilizing all outputs and additional amplifiers? Another option would be to consider having a separate volume for the line level outputs for use with subwoofer amplifiers. You could then control the subwoofer from Amplipi separately from the speakers.

**Comment by Lohrer** [comment]
This is already fixed in #196. If you would like to flash the un-released firmware to get this fix immediately, check out the [firmware programming guide](https://github.com/micro-nova/AmpliPi/blob/main/fw/preamp/README.md)

That said the line outputs and amplified outputs are unfortunately not controlled separately in the current design. Anything played on the amplified output of a zone will also be played on the corresponding preout, and at the same volume setting. There are some discussions in #155 already, but the main point was to check out the [signal flow diagram](https://github.com/micro-nova/AmpliPi/blob/main/hw/diagrams/signal_diagram.drawio.svg) to see how the audio signal gets sent through hardware.
