### ISSUE TITLE
Make a script to toggle appliance type from pi -> pro within new Preamp EEPROM

### ISSUE THREAD

**Issue by Lohrer** [micro-nova/AmpliPi#543]
Make a desktop shortcut on manufacturing computers.

Needs to support both the main unit and expanders.

**Comment by Lohrer** [comment]
Since we decided not to distinguish a 'pi' vs 'pro', I think this is no longer needed, can you verify @rtertiaer?

**Comment by rtertiaer** [comment]
I imagined this more as a hardware detection concern than a branding concern. This issue was created back when our hardware had pro versus pi distinctions based on hardware model.

Barring identifying things as a big box versus a streamer, it would be extremely nice if eeprom could identify what particular model boards went into it, without us necessarily probing hardware - akin to loading a device tree versus enumerating devices on a bus. This would give us an immense amount of flexibility going forward to tolerate hardware changes in software easily, as well as properly diagnose and support devices with bugs in the field.

**Comment by rtertiaer** [comment]
We convened IRL about this. I was a smidge mistaken about the root of this ticket, which was to distinguish between Pi and Pro branded versions of _the same hardware_. What I'm describing above, whereupon the eeproms in each appliance state what each appliance contains in terms of hw revs, is something we'll work towards implementing iteratively. At present, each board that has an eeprom (streamer support board and newer preamp boards) will identify what revision of hardware that particular board is, as well as an appliance serial number; these two bits of info are enough for our support to do correlation with orders and determine exact hw revisions of the other boards in the box. I also learned that we are intending to put eeproms on more of the boards which identify hw rev & serial as well, which will dramatically shorten that feedback loop going forward - this functionality has my strong vote.

Given all that, this ticket probably actually is obsolete. Closing.
