### ISSUE TITLE
Potential Feature: snapcast

### ISSUE THREAD

**Issue by bs42** [micro-nova/AmpliPi#72]
[Snapcast](https://github.com/badaix/snapcast) support

> Snapcast is a multi-room client-server audio player, where all clients are time synchronized with the server to play perfectly synced audio.

The idea is that the AmpliPi could be either a client or a server for snapcast.  For larger locations you could have 2 AmpliPis in different locations powering lots of zones but minimizing wiring issues/distance.  For some homes you could have the home on an AmpliPi+extenders, and portable speaker(s) or a pi+amp powering a backyard zone.

**Comment by linknum23** [comment]
Snapcast is an awesome open source project for distributed wireless speakers! We've been following their progress for a while now, it looks really useful for apartment and other setups where you would use mostly wireless speakers.

In the future AmpliPi could host a snapcast server to add support for wireless speakers. The only issue with this, using the current hardware, is that only digital sources and streams would be playable (the analog RCA inputs connect directly to the audio muxes). We think this would still add a lot of flexibility for mixed speaker setups.

Using AmpliPi as a snapcast client is a cool idea as well. The AmpliPi could potentially host up to 4 snapcast clients. In this case we would recommend routing each snapcast client to a group of zones, since each of AmpliPi's zones wouldn't be individually discoverable without significant changes to how snapcast's protocol works.

Also although synchronizing 2 AmpliPi's over the network might be possible, we have not designed the software with this use case in mind. 

Which of these would be the most useful? Feel free to make an issue for either client or server support.
