### ISSUE TITLE
Stream input fields do not match font-family for the rest of the app

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#777]
![image](https://github.com/micro-nova/AmpliPi/assets/7657783/289272af-304d-47e1-b139-f4f322cd850c)

This changed recently, and while the fields look wayyyy better than the old variety, it still does not look good.

**Comment by SteveMicroNova** [comment]
I imagine this was caused during [PasswordSecurity](https://github.com/micro-nova/AmpliPi/pull/716/files), specifically when I replaced our bespoke TextField with the Material UI variant

To chase this breadcrumb trail, use [the docs for the component](https://mui.com/material-ui/react-text-field/) to see how to control the font, I'm sure you can add a className but if that doesn't work the sx prop should work (it's like the style prop but passes stuff down to the children instead)

I self assign this, but will be out for 10 business days. Follow this breadcrumb trail if you feel it's worth solving while I'm gone; otherwise consider this comment a note to self for me.

**Comment by rtertiaer** [comment]
Closed with #800
