### ISSUE TITLE
Song names have "'" around commas in ui

### ISSUE THREAD

**Issue by klay2000** [micro-nova/AmpliPi#792]
Specific song I noticed this on:
https://open.spotify.com/track/26ykYX8xQgECWm5ax7iVrX?si=ZiZAmdfASYiMbnugVhIDlg&nd=1&dlsi=2a5be70185774f14

This could just be a spotify bug, but I'm assuming this happens everywhere.

**Comment by SteveMicroNova** [comment]
![Image](https://github.com/user-attachments/assets/70423814-2d2d-4583-bce9-27cc1bff07fb)

This does not occur on a Pandora song streamed via Airplay

**Comment by SteveMicroNova** [comment]
![Image](https://github.com/user-attachments/assets/8154abc6-7230-4b09-b1f0-62770be76b32)


This does not occur on spotify songs, either

I'm guessing it's a spotify specific issue that relates to how they concatenate multiple artist names rather than having a discreet string that contains them both (this makes more sense if you look at the spotify ui yourself)
