### ISSUE TITLE
Stream selection header in settings truncated in small iOS

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#898]
![IMG_0043](https://github.com/user-attachments/assets/ca799510-49b5-4ff9-9aaf-0818e905858b)

The device is an iPhone 12 Mini running iOS 17.5.1.

**Comment by rtertiaer** [comment]
This is actually true for all of the individual submenus in settings, not just streams.

**Comment by SteveMicroNova** [comment]
This seems to be Issue #554, solved in #767

**Comment by rtertiaer** [comment]
I was testing off main's `HEAD`, commit 2eb34a1170eca267fed6868aa4175e664c4796ad; it would seem that PR was an incomplete fix.

**Comment by SteveMicroNova** [comment]
Taking this on, going to start writing notes in here as I investigate

First note is that this is fixed in the app, but not in web browsers
It is worse on mobile chrome than mobile safari

App:
![Image](https://github.com/user-attachments/assets/40cca902-b729-49cf-b15e-31a39d7f0490)


Safari:
![Image](https://github.com/user-attachments/assets/cf89eda8-3a5f-42ed-b670-891720cd8d7c)


Chrome:
![Image](https://github.com/user-attachments/assets/b0504687-b78f-43b0-85a6-5fe366ff162b)

**Comment by rtertiaer** [comment]
fwiw chrome on ios is actually just a reskinned safari with extra spying

**Comment by Lohrer** [comment]
> Mobile firefox is completely fine

It's cut off on my mobile firefox.

**Comment by SteveMicroNova** [comment]
> It's cut off on my mobile firefox.

🥴
